version: '3'
services:
    laravel.test:
        build:
            context: ./docker/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2-sqlsrv
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - sqlsrv
    sqlsrv:
        image: 'mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04'
        ports:
            - '${DB_PORT:-1433}:1433'
        environment:
            SA_PASSWORD: '${DB_PASSWORD}'
            ACCEPT_EULA: 'Y'
        volumes:
            - 'sail-sqlsrv:/var/opt/mssql'
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-sqlsrv:
        driver: local
